//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseTab
    {
        public int CaseId { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CaseStatus { get; set; }
        public string UserText { get; set; }
        public string AdminText { get; set; }
        public string CaseName { get; set; }
    
        public virtual Transactions Transactions { get; set; }
        public virtual Users Users { get; set; }
    }
}
