//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserChat
    {
        public int DialogId { get; set; }
        public string UserText { get; set; }
        public Nullable<int> CaseId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual CaseTab CaseTab { get; set; }
        public virtual Users Users { get; set; }
    }
}
